[package]
org = "wso2"
name = "enterprise_client_onboarding_sync"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.associations"
version = "0.1.0"
repository = "local"
